TITEL = "(Martin, 2021)"

CONTENT = ("## Anmerkung: \n"
           "Dies ist Knoten für Literaturquellen. Hierbei sind folgende "
           "Informationen für ***Bücher*** essenziell:\n\n"
           "**- Autor:**\n Der vollständige Name des Autors.\n\n"
           "**- Erscheinungsjahr:**\n Das Jahr, in dem das Buch veröffentlicht "
           "wurde.\n\n"
           "**- Titel des Buches:**\n Der vollständige Titel des Buches, eventuell "
           "inklusive Untertitel.\n\n"
           "**- Auflage:**\n Inhalt kann sich mit den verschieden Auflagen "
           "eines Buches unterscheiden. Daher ist es wichtig die Auflage anzugeben, "
           "auf die Sie sich beziehen. \n\n"
           "**- Ort der Veröffentlichung:**\n Die Stadt, in der der Verlag seinen "
           "Sitz hat."
           "**- Verlag:**\n Der Name des Verlags.\n\n"
           "\n## Beispiel\n"
           "\n### Autor:\n"
           "Martin, R.C."
           "\n### Veröffentlichungsjahr:\n"
           "2021"
           "\n### Titel:\n"
           "Clean Craftsmanship: Disciplines, Standards, and Ethics"
           "\n### Auflage:\n"
           "1. Auflage"
           "\n### Ort:\n"
           "Boston"
           "\n### Verlag:\n"
           "Addison-Wesley Professional")
