TITEL = "(Gruber, 2004)"

CONTENT = ("## Anmerkung: \n"
           "Dies ist Knoten für Online-Quellen. In diesem konkreten Fall für Markdown "
           "als Internet Quelle. Hierbei wird die offizielle Website des Entwicklers "
           "von Markdown verwendet. Eine Website als Quelle ist legitim, wenn sie "
           "bestimmte Kriterien der Glaubwürdigkeit und Zuverlässigkeit erfüllt. "
           "Kriterien hierfür sind: \n\n"
           "**- Expertise:**\n"
           "Überprüfen Sie, wer hinter der Website steht. Ist es eine anerkannte "
           "Institution, eine Bildungseinrichtung oder ein Experte auf dem Gebiet? \n\n"
           "**- Aktualität:**\n"
           "Überprüfen Sie das Datum der Veröffentlichung oder der letzten "
           "Aktualisierung. Für viele Themen ist es wichtig, dass die Informationen "
           "aktuell sind. \n\n"
           "**- Genauigkeit und Zuverlässigkeit:**\n"
           "Enthält die Website präzise Informationen, die mit anderen glaubwürdigen "
           "Quellen übereinstimmen? Websites, die sorgfältig recherchiert und mit "
           "Belegen untermauert sind, sind in der Regel vertrauenswürdiger.\n\n"
           "**- Zweck und Objektivität:**\n"
           "Beurteilen Sie den Zweck der Website. Ist sie darauf ausgerichtet, "
           "objektive Informationen zu liefern, oder verfolgt sie kommerzielle, "
           "politische oder ideologische Ziele? Objektive, unparteiische Quellen sind "
           "generell vertrauenswürdiger.\n\n"
           "**- Transparenz:**\n"
           "Gute Quellen bieten oft Informationen über ihre Autoren, Finanzierung, "
           "Mission und den Prozess der Inhaltsprüfung.\n\n"
           "\n## Beispiel\n"
           "\n### Autor:\n"
           "Gruber, John"
           "\n### Jahr:\n"
           "2004"
           "\n### Titel:\n"
           "Markdown"
           "\n### Verfügbar unter:\n"
           "https://daringfireball.net/projects/markdown/"
           "\n### Zugriff am:\n"
           "11. November 2023")
