TITEL = "(Dijkstra, 1972)"

CONTENT = ("Für wissenschaftliche Veröffentlichungen (***Paper***) sind folgende "
           "Angaben notwendig:\n\n"
           "**- Autor(en) des Papers:**\n Die Namen der Autoren, in der "
           "Reihenfolge, in der sie im Paper aufgeführt sind.\n\n"
           "**- Jahr der Veröffentlichung:**\n Das Jahr, in dem das Paper "
           "veröffentlicht wurde.\n\n"
           "**- Titel des Papers:**\n Der vollständige Titel des Papers.\n\n"
           "**- Titel der Zeitschrift oder Konferenz:**\n Der Name der Zeitschrift "
           "oder der Konferenz, in der das Paper veröffentlicht wurde.\n\n"
           "**- Bandnummer(Ausgabennummer):**\n Die Band- und Ausgabennummer der "
           "Zeitschrift, in der das Paper erschien.\n\n"
           "**- Seitenzahlen:**\n Die Seitenzahlen des Papers in der Zeitschrift."
           "**- URL:**\n Falls das Paper online verfügbar ist, fügen Sie die URL "
           "hinzu.\n\n"
           "**- Zugriff am:**\n Das Datum, an dem Sie auf das Paper zugegriffen "
           "haben, falls es online verfügbar ist.\n\n"
           "\n## Beispiel\n"
           "\n### Autor:\n"
           "Dijkstra, E.W."
           "\n### Veröffentlichungsjahr:\n"
           "1972"
           "\n### Titel:\n"
           "The Humble Programmer"
           "\n### In:\n"
           "Communications of the ACM"
           "\n### Bandnummer(Ausgabennummer):\n"
           "15(10)"
           "\n### Seitenzahlen:\n"
           "859-866")
