# id:60

TITEL = "Audi"

CONTENT = (
"## Beschreibung:\n"
"Die Audi AG ist ein deutscher Automobilhersteller, der sich auf die Herstellung von Premium-Autos spezialisiert hat [1]. Das Unternehmen wurde 1909 von August Horch gegründet und gehört seit den 1960er Jahren zum Volkswagen-Konzern [2]. Audi steht für sportliche Fahrzeuge, hochwertige Verarbeitung und progressives Design. Der Audi Konzern ist einer der erfolgreichsten Hersteller von Automobilen im Premiumsegment. Audi hat eine breite Palette von Fahrzeugen, von Limousinen und Sportwagen bis hin zu SUVs und Elektroautos. Audi ist auch bekannt für seine technologischen Innovationen, einschließlich Quattro-Allradantrieb, Aluminiumkarosserietechnologie und TFSI-Motorentechnologie. Audi hat sich auch dem Umweltschutz verschrieben und arbeitet an der Entwicklung von Elektro- und Hybridfahrzeugen [1].\n"
"\n"
"## Warum ist Audi für Informatiker interessant?:\n"
"Audi ist für Informatiker interessant, da das Unternehmen in wegweisende Technologien wie autonomes Fahren, Elektromobilität und digitale Konnektivität investiert. Informatiker haben die Gelegenheit, an der Entwicklung von Fahrzeugsoftware, Assistenzsystemen und digitalen Cockpits teilzunehmen. Audi bietet somit eine attraktive Umgebung, um innovative Lösungen für die zukünftige Mobilität zu gestalten.\n"
"\n"
"## Historie:\n"
"Die Geschichte der Audi AG reicht bis ins 19. Jahrhundert zurück. August Horch gründete 1899 sein erstes Automobilunternehmen, August Horch & Cie, in Köln. Kurz darauf, im Jahr 1909, gründete er ein neues Automobilunternehmen in Zwickau, das seit 1910 unter dem Namen Audiwerke AG, Zwickau, firmiert. Nach dem Zweiten Weltkrieg wurde 1949 eine neue Auto Union GmbH in Ingolstadt (Bayern) gegründet[3]. Dort liefen, neben DKW-Motorrädern, zunächst Schnellaster vom Band und ab 1950 baute das neue Werk Düsseldorf-Derendorf die F-89-Pkw, beides Modelle mit Frontantrieb [2]. Im Laufe der Jahre hat Audi eine Reihe von Meilensteinen erreicht. 1980 führte Audi den Quattro-Allradantrieb ein, eine Technologie, die das Fahren unter schwierigen Bedingungen revolutionierte.\n"
"\n"
"## Mission/Ziel:\n"
"Die Unternehmensstrategie von Audi, “Vorsprung 2030”, zielt darauf ab, die Zukunftsfähigkeit von Audi zu sichern und die Transformation in ein neues Mobilitätszeitalter maßgeblich mitzugestalten [5]. Audi CEO Markus Duesmann betont, dass das Tempo der Veränderungen in unserer Gesellschaft rasant zunimmt, daher beschleunigt Audi seine Transformation [4].\n"
"\n"
"**Website:**\n"
"https://www.audi.com/de.html\n"
"\n"
"**Mitarbeiterzahl:**\n"
"Im Jahr 2022 waren bei Audi rund 88.000 Menschen beschäftigt [5].\n"
"\n"
"**Praxissemester/Praktikum:**\n"
"Ja\n"
"\n"
"**Kontakt:**\n"
"https://karriere.audi.de/sap/bc/bsp/sap/z_hcmx_ui_ext/desktop.html#/SEARCH/RESULTS\n"
"\n"
"**Quellen:**\n"
"*-[Image] www.....\n"
"*-[1] https://www.audi.com/de/company/profile/history.html\n"
"*-[2] https://de.wikipedia.org/wiki/Audi\n"
"*-[3] https://www.audi.com/de/company/profile/history/cornerstone.html\n"
"*-[4] https://www.kulturgut-mobilitaet.de/aktuell/hist-mobilitaet/494-100-jahre-audi-eine-premiummarke-mit-geschichte\n"
"*-[5] https://www.audi.com/de/company.html\n"
)

IMAGE_NAME = "audi_logo.png"