# id:26

TITEL = "NextKraftwerke GmbH"

CONTENT = (
    "## Beschreibung:\n"
    "Die Firma „Next Kraftwerke“ wurde 2009 gegründet und betreibt als digitaler Versorger eines der größten "
    "virtuellen Kraftwerke in Europa.\n "
    "Virtuelle Kraftwerke sind Zusammenknüpfungen von unabhängigen Stromproduzenten, wie z.B. Private Haushalte sowie "
    "Unternehmen.\n "
    "Unter Virtuellen Kraftwerken versteht man die Zusammenschaltung von kleinen, dezentralen Stromerzeugern bzw. "
    "Lieferanten und daraufhin Zentraler Steuerung. „Virtuell“ stimmt in der direkten Bedeutung nicht; es sind "
    "physische Verbindungen.\n "
    "Mit über 10.000 MW, woraus über 6.000 MW aus Solarstrom stammen,"
    "ist Next Kraftwerke der größte Photovoltaik Direktvermarkter aus Deutschland.\n"
    "\n"
    "## Warum ist Next Kraftwerke für Informatiker interessant?:\n"
    "Die Next Kraftwerke spielen eine wichtige Rolle für die Energiewende in Deutschland und außerhalb, zudem bieten "
    "sie viele verschiedene Stellen die einem die möglichkeit gibt das Unternehmen nicht verlassen zu müssen.\n "
    "\n"
    "Historie:\n"
    "Next Kraftwerke wurde 2009 als Start-up gegründet mit der Idee, verschiedene volatile Energiequellen zu Bündeln "
    "um Schwankungen im Stromnetz auszugleichen.\n "
    "Die Gründer Arbeiteten vorher im Energiewirtschaftlichen Institut der Universität zu Köln.\n"
    "\n"
    "Mission/Ziel:\n"
    "Das Ziel der Next Kraftwerke ist es Unternehmen sowie Privatnutzern die Möglichkeit bei der Energiewende zu "
    "unterstützen\n "
    "\n"
    "**Website:**\n"
    "next-kraftwerke.de\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "250+\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Nein\n"
    "\n"
    "**Kontakt:**\n"
    "+49 221/ 82 00 85 - 0\n"
    "\n"
    "**Quellen:**\n"
    "*-[1]next-kraftwerke.com\n"
    "*-[2]https://link.springer.com/chapter/10.1007/978-3-658-23204-7_20\n"
    "*-[3] https://www.next-kraftwerke.de/download-center\n"
)
IMAGE_NAME = "nextkraftwerke_logo.png"
