# id:36

TITEL = "OBI GmbH & Co. KG"

CONTENT = ("**Beschreibung:**\n"
           "OBI ist ein führendes Unternehmen im Bereich Bau- und Heimwerkerbedarf, das sich darauf konzentriert, seinen Kundinnen und Kunden in Deutschland und Europa zu helfen, ihre Wohnräume optimal zu gestalten. Neben dem deutschen Heimatmarkt ist OBI in neun weiteren europäischen Ländern präsent, darunter Bosnien-Herzegowina, Italien, Österreich, Polen, Schweiz, Slowenien, Slowakei, Tschechische Republik und Ungarn. Mit über 40.000 Mitarbeiterinnen und Mitarbeitern betreibt OBI mehr als 640 Märkte in insgesamt zehn Ländern, wovon rund 350 Märkte in Deutschland zu finden sind.\n\n"
           "Die Werte von OBI, die als Schaffensfreude, Gemeinschaft, Entwicklung und Eigenverantwortung definiert sind, bilden einen integralen Bestandteil der Unternehmensidentität und dienen als Leitprinzipien für Arbeitsweise und Handeln. Diese Werte spiegeln sich in der Unternehmenskultur wider und verbinden die Vergangenheit mit der Zukunft.\n\n"
           "OBI betrachtet das Zuhause nicht nur als vier Wände, sondern als einen Ort der Emotionen, an dem das Leben gestaltet und die Persönlichkeit entfaltet wird. Die Mission des Unternehmens besteht darin, die Kundinnen und Kunden auf dem Weg zu ihrem perfekten Zuhause zu begleiten und zu befähigen. Dabei setzt OBI auf eine enge Verbindung zwischen Kundinnen und Kunden, dem passenden Angebot und den besten Expertinnen und Experten, sowohl digital als auch vor Ort. [1][2][3]\n"
           "\n"
            "**Website:**\n"
            "-https://www.obi.de\n"
            "-https://jobs.obi.de\n"
            "\n"
            "**Historie:**\n"
           "Die Erfolgsgeschichte der OBI Bau- und Heimwerkermärkte begann im Jahr 1970 mit der Eröffnung eines 870 m² großen Marktes im Einkaufszentrum Alstertal in Hamburg-Poppenbüttel. Zu dieser Zeit waren insgesamt 12 Mitarbeiter im ersten OBI Markt beschäftigt, zusätzlich zu den Mitarbeiterinnen und Mitarbeitern in der Systemzentrale in Wermelskirchen.\n\n"
           "Die Ursprungsidee von \"Do-it-yourself-Märkten\" wurde von Dr. Emil Lux und Manfred Maus in den späten 60er Jahren in Wermelskirchen konzipiert, nachdem sie das erfolgreiche Geschäftsmodell in den USA entdeckt hatten. In den USA boten Do-it-yourself-Geschäfte eine breite Palette von Baumaterialien und Heimwerkerprodukten unter einem Dach an, und die Idee des \"One-Stop-Shoppings\" begeisterte Lux und Maus.\n\n"
           "In Deutschland war es zu dieser Zeit üblich, spezialisierte Fachgeschäfte für verschiedene Baumarktprodukte aufzusuchen. Lux und Maus wollten diese Norm brechen und schufen den ersten OBI Markt, der Kunden alles aus einer Hand bot. Die Geschäftsidee der \"12 Fachgeschäfte unter einem Dach\" wurde erfolgreich getestet und anschließend franchisiert. Die Anzahl der OBI Märkte wuchs stetig, und bis 1975 gab es bereits 16 Bau- und Heimwerkermärkte in Deutschland. Der Werbeslogan \"Bei Eisen-Karl ... oder bei OBI\" unterstrich die Grundidee des One-Stop-Shoppings.\n\n"
           "Der Name \"OBI\" und das damit verbundene Biberlogo haben seit jeher Spekulationen ausgelöst. Es handelt sich jedoch nicht um eine Abkürzung, sondern um die \"Lautschrift\" des französischen Wortes \"Hobby\". Manfred Maus erwarb die Wort-Bild-Marke Ende der 60er Jahre in Frankreich und ließ sie weltweit – mit Ausnahme von Frankreich – als Marke registrieren.\n\n"
           "Heute ist OBI ein international tätiges Unternehmen mit 330 Märkten im Inland und 175 im Ausland. Neben Deutschland ist OBI in mehreren Ländern, darunter Bosnien, Italien, Österreich, Polen, Russland, der Schweiz, Slowenien, der tschechischen Republik, Ungarn und Kroatien vertreten. Die Expansion in weitere osteuropäische Länder ist geplant, und der Markteintritt in die Ukraine steht bevor. Das Unternehmen beschäftigt über 38.000 Mitarbeiterinnen und Mitarbeiter und erzielte im Geschäftsjahr 2006/2007 einen Bruttoumsatz von 5,8 Milliarden Euro. [1]\n"
           "\n"
           "**Mission/Ziele:**\n"
           "Die Vision von OBI ist es, die erste Anlaufstelle für alle Fragen und Projekte rund um das eigene Zuhause in Europa zu sein. Dabei übernimmt das Unternehmen auch Verantwortung im Bereich Umweltschutz und gesellschaftlicher Fortschritt. OBI ermöglicht es den Kundinnen und Kunden, ökologisch bessere Entscheidungen für ihre Projekte zu treffen, zum Beispiel durch torffreie Erde, fachgerechte Entsorgung und die Reduktion von lösungsmittelhaltigen Produkten im Sortiment. Durch Kooperationen, Kampagnen und Projekte setzt OBI ein Zeichen für den gesellschaftlichen Zusammenhalt und engagiert sich vielfältig in sozialen Einrichtungen und Bildungspartnerschaften. Das Unternehmen strebt eine ressourcenschonende Gestaltung an und setzt sich für einen respektvollen Umgang mit der Umwelt und der Natur ein, insbesondere durch den Schutz des Klimas und die Reduktion von Abfällen. [2][3]\n"
           "\n"
            "**Mitarbeiterzahl:**\n"
           "Mit einer Belegschaft von 40.000 Mitarbeiterinnen und Mitarbeitern betreibt das Unternehmen erfolgreich über 640 Märkte in zehn verschiedenen Ländern. Davon befinden sich rund 350 Märkte allein in Deutschland. [3]\n"
           "\n"
            "**Kontakt:**\n"
           "-https://jobs.obi.de/\n"
           "\n"
            "**Quellen:**\n"
            "-http://www.wiwi-online.de/download/padowns/obi%20historie.pdf [1]\n-https://www.obi.de/pages/verantwortung [2]\n-https://jobs.obi.de [3]")

IMAGE_NAME = "obi_logo.png"