# id:36

TITEL = "OBI GmbH & Co. KG"

CONTENT = ("Die Erfolgsgeschichte von OBI begann im Jahr 1970 mit der Eröffnung eines 870 m² großen Marktes im Einkaufszentrum Alstertal in Hamburg-Poppenbüttel. Mit insgesamt 12 Mitarbeitern startete das Unternehmen, wobei die Systemzentrale in Wermelskirchen zusätzliche Unterstützung bot. Die Gründer, Dr. Emil Lux und Manfred Maus, hatten die Vision, das erfolgreiche Geschäftsmodell der \"Do-it-yourself-Märkte\" aus den USA nach Deutschland zu bringen."
            "In den USA hatten Do-it-yourself-Geschäfte bereits bewiesen, dass Selbstbedienungsläden, die alle Sortimente zum Bauen und Heimwerken unter einem Dach anbieten, erfolgreich sein können. Diese Idee des \"One-Stop-Shoppings\" begeisterte Lux und Maus. In Deutschland war es zu dieser Zeit üblich, in spezialisierten Fachgeschäften einzukaufen, was sie ändern wollten. Der erste OBI Markt setzte die Geschäftsidee der \"12 Fachgeschäfte unter einem Dach\" um und wurde nach einer erfolgreichen Testphase franchisiert."
           "Die Anzahl der OBI Märkte stieg kontinuierlich an, und bereits 1975 gab es 16 Bau- und Heimwerkermärkte in Deutschland. Der Slogan \"Bei Eisen-Karl ... oder bei OBI\" verdeutlichte werblich die Grundidee des \"One-Stop-Shoppings\". Der Name \"OBI\" und das damit verbundene Biber-Symbol haben eine interessante Herkunft. Entgegen vieler Vermutungen handelt es sich nicht um eine Abkürzung, sondern um die \"Lautschrift\" des französischen Wortes \"Hobby\". Manfred Maus erwarb die Wort-Bild-Marke Ende der 60er Jahre in Frankreich und ließ sie weltweit, mit Ausnahme von Frankreich, als Marke eintragen."
            "Heute ist OBI ein bedeutendes Unternehmen mit über 330 Märkten im Inland und weiteren 175 im Ausland. Die internationale Präsenz erstreckt sich über Bosnien, Italien, Österreich, Polen, Russland, die Schweiz, Slowenien, die tschechische Republik, Ungarn und Kroatien. Die Expansion in weitere osteuropäische Länder ist geplant, und der Markteintritt in die Ukraine steht bevor. Mit einer beeindruckenden Mitarbeiterzahl von über 38.000 und einem Bruttoumsatz von 5,8 Milliarden Euro im Geschäftsjahr 2006/2007 bleibt OBI ein führender Anbieter im Bau- und Heimwerkermarkt. Weitere Informationen zum Unternehmen sind auf ihrer Website https://www.obi.com verfügbar.")

IMAGE_NAME = "obi_logo.png"