TITEL = "parcIT GmbH"

CONTENT = ("## Beschreibung:\n"
"Die parc IT GmbH ist ein führendes Unternehmen in der Entwicklung von innovativen Softwarelösungen im Bereich des Bankenwesens. Mit einem klaren Fokus auf Qualität, kontinuierliche Verbesserung und Mitarbeiterengagement hat sich das Unternehmen als herausragender Akteur in der Branche etabliert. [1] Durch Ihre Leistungen hat die parcIT GmbH es geschafft mehrere Auszeichungen unteranderem von Kununu zu erhalten. [1] \n"
"\n"

"## Historie:\n"
"Die parcIT GmbH blickt auf eine beeindruckende Historie zurück, die von bedeutsamen Meilensteinen geprägt ist. Im Jahr 1989 begann die Reise als Software-Sparte der ifb AG in Münster, mit einem klaren Fokus auf das Risikomanagement in Banken. Klaus Wiegand, damaliger Absolvent, erzielte den ersten Erfolg mit der Software \"ROI-Kennzahlen-Analyse\". Nach dem Umzug nach Köln und der Festanstellung der ersten Mitarbeiter entwickelte sich der Software-Bereich der ifb zu einem bedeutenden Player im Markt. Im Jahr 2001 erhielt die parcIT den Auftrag für die vollständige Software-Suite VR-Control, ein entscheidender Meilenstein, der das Unternehmen nachhaltig prägte. 2009 erfolgte der Verkauf der Softwaresparte an die Fiducia IT AG, und die parcIT GmbH wurde als Tochterunternehmen gegründet. Der Name \"parcIT\" entstand durch einen internen Namenswettbewerb und spiegelt den Teamgeist wider. Die parcIT beherbergt seitdem die Software-Suite VR-Control, auch bekannt als okular, die deutschlandweit von über 1.100 Banken in Risikosteuerung und Gesamtbanksteuerung eingesetzt wird. In 2015 erweiterte sich das Produktportfolio um die Kreditrisikoverfahren Rating und Kreditportfoliomodelle der Genossenschaftlichen FinanzGruppe. Diese Verfahren wurden erstmals in die Verantwortung der parcIT übergeben, was zu personellem Zuwachs und weiterem Wachstum führte. Die Zentralisierung sämtlicher VR-Control-Bestandteile bei der parcIT im April 2019 verstärkte diesen Trend. Der Standort Bayenwerft wurde durch den neuen Standort Kaiserhof am Kölner Mediapark ersetzt. Die Dreierspitze, bestehend aus Heinz-Otto Krauskopf, Klaus Wiegand und Patrick Yousefian, schätzt das Vertrauen des Verbundes, der Kunden und Partner. Nach 30 Jahren Erfahrung und 10 Jahren als parcIT betonen sie die Leistungsfähigkeit und Konsistenz des Unternehmens, die auf dem hohen Engagement und Zusammenhalt der Mitarbeiter basiert. Mit rund 260 Mitarbeiterinnen und Mitarbeitern blickt die parcIT zuversichtlich in die Zukunft und dankt allen, die zum Erfolg beitragen.[2]\n"
"\n"

"## Mission/Ziel:\n"
"Die parc IT GmbH bietet eine breite Palette von innovativen Softwarelösungen an, die darauf abzielen, die Bedürfnisse im Finanzsektor umfassend zu erfüllen. Hier sind die wichtigsten Produkte und Lösungen des Unternehmens: Die okular-Softwaresuite erlebt regelmäßige halbjährliche Hauptreleases, die den Kunden funktionale Erweiterungen und Verbesserungen bieten. Die Umstellung auf dieses Veröffentlichungsmodell zielt darauf ab, kürzere Ausbringungszeiten, geringere Komplexität pro Release und eine nachhaltigere Qualitätsabsicherung zu gewährleisten. Erweiterte Gesamtbanksteuerungsplattform (EGP): EGP ist eine integrierte Gesamtbanksteuerungsplattform, entwickelt in Zusammenarbeit mit den Konzernen Fiducia & GAD IT und msg. Sie verbindet Accounting, Meldewesen und Risikosteuerung/Controlling über einen einheitlichen Datenhaushalt und zentrale Methoden. EGP erfüllt die Prinzipien von BCBS 239 und bietet eine einheitliche Datenbasis für verschiedene Aspekte der Banksteuerung. Adressrisikosteuerung: Die parc IT GmbH unterstützt Finanzinstitute bei der effektiven Steuerung von Adressrisiken im Kunden- und Eigengeschäft. Dies beinhaltet Kreditstrukturanalysen, die Höhe und Entwicklung von Kreditherauslagen beschreiben, sowie die Analyse von Ursachen auffälliger Risikowerte auf verschiedenen Granularitätsebenen. Kreditportfoliomodelle: Das Unternehmen bietet Modelle zur Messung unerwarteter Verluste im Rahmen der Adressrisikosteuerung. Dazu gehören das analytische Modell CreditRisk+ für reine Ausfallrisiken sowie Simulationsmodelle wie Credit Metrics für komplexe Migrations- und Spreadrisiken. Liquiditätsrisiko: Die parc IT GmbH adressiert das Liquiditätsrisiko durch die Erzeugung verschiedener Liquiditätsablaufbilanzen und die Berechnung der Liquidity Coverage Ratio (LCR). Die Simulation des Liquiditätsverhaltens und die Berücksichtigung von Liquiditätstransferpreisen tragen zur Optimierung des Liquiditätsmanagements bei. Risk-Return-Steuerung: Das Unternehmen bietet Lösungen zur Optimierung des Risiko-Rendite-Profils von Banken. Dies beinhaltet die Festlegung von Strukturlimiten, die strategische Vermögensanlage unter Berücksichtigung von erwarteten Erträgen und Risiken sowie die Performance- und Risiko-Messung für eine gezielte Steuerung von Risiken. Alles in allem besitzt die parc IT GmbH eine umfassende Produktpalette, die darauf abzielt, Finanzinstitute in verschiedenen Aspekten ihres Geschäfts effektiv zu unterstützen und regulatorischen Anforderungen gerecht zu werden.[1]\n"
"\n"

"**Website:**\n"
"https://www.parcit.de/\n"
"\n"

"**Mitarbeiterzahl:**\n"
"Die parcIT GmbH verfügt zur Zeit über 400 Mitarbeiter.[3]\n"
"\n"

"**Quelle:**\n"
"-[1]https://www.parcit.de/\n"
"-[2]https://www.parcit.de/10-jahre-parcit-30-jahre-erfahrung/#:~:text=1989%20startete%20die%20Keimzelle%20der,Klaus%20Wiegand%20den%20ersten%20Erfolg.\n"
"-[3]https://www.parcit.de/ueber-parcit/karriere/#:~:text=Bei%20der%20parcIT%20vereint%20diese,Datamanagement%2C%20Systemtechnik%20und%20viele%20weitere.\n"
"-Bild: https://www.vr-karriere.de/profil/649\n")

IMAGE_NAME = "parcIT_logo.png"