# id:16

TITEL = "Rhenag Rheinische Energie AG"

CONTENT = (
"## Beschreibung:\n"
"Rhenag ist ein Stadtwerk welches Energie produziert und verkauft. Sie produzieren mit Wasserkraftwerken sowie mit Wind und Solarenergie erneuerbaren Strom.\n"
"Die Rhenag sorgt für nachhaltige und effiziente Energieversorgung und hilft ihren Kunden dabei ihren Stromverbraucht zu optimieren\n"

"\n"
"## Warum ist die Rhenag für Informatiker interessant?:\n"
"Die Rhenag bietet viele verschiedene Arbeitsstellen im Bereich IT, und ist ein Energiekonzern der grüne Energie produziert und vermarktet.\n"
"\n"
"## Historie:\n"
"Die Rhenag ist eines der ältesten deutschen Energieversorgungsunternehmen und wurde im Jahre 1872 gegründet.\n"
"Damals wurde sie gegründet, um eine zentrale Wasserversorgung zu errichten\n"
"## Mission/Ziel:\n"
"Ihr Ziel ist es die Energie der Zukunft zu gestalten, mithilfe von, unteranderem, Erneuerbarer Energie wie Solarstrom, Wasserkraft sowie Windkraft.\n"
"\n"
"**Website:**\n"
"rhenag.de\n"
"\n"
"**Mitarbeiterzahl:**\n"
"300+\n"
"\n"
"**Praxissemester/Praktikum:**\n"
"Nein\n"
"\n"
"**Kontakt:**\n"
"0221 93731-0\n"
"\n"
"**Quellen:**\n"
"*-[Image] rhenag.de\n"
"*-[1] rhenag.de\n"
)
IMAGE_NAME = "rhenagrheinischeenergie_logo.png"