# id:35

TITEL = "Riot Games Inc."

CONTENT = ( "**Beschreibung:**\n"
            "Riot Games, mit Hauptsitz in West Los Angeles, ist ein US-amerikanischer Entwickler und Publisher von Computerspielen. Bekannt ist das Unternehmen insbesondere für das MOBA (Multiplayer Online Battle Arena) League of Legends, das am 27. Oktober 2009 in Europa und Nordamerika veröffentlicht wurde. Seit dem Abschluss des Unternehmensanteilkaufs im Dezember 2015 ist Riot Games eine Tochtergesellschaft des chinesischen Internetkonzerns Tencent. [1][4]"
            "\n\n"
            "**Website:**\n"
            "-https://www.riotgames.com/de"
            "\n\n"
            "**Historie:**\n"
            "Die Historie von Riot Games veranschaulicht eine beeindruckende evolutionäre Entwicklung, eingeleitet im späten ersten Jahrzehnt des 21. Jahrhunderts. Die Unternehmensgenese fokussierte sich primär auf die Kreation von League of Legends (LoL), einem Multiplayer Online Battle Arena (MOBA)-Spiel, das durch ein ausgeklügeltes Geschäftsmodell und eine kontinuierliche Spieleransprache in den Vordergrund rückte."
            "\n\n"
            "Die Gründung von Riot Games im Jahr 2006 durch die Business-Studenten Brandon \"Ryze\" Beck und Marc \"Tryndamere\" Merrill zeugte von einem strategischen Ansatz, der nicht nur die Integration bewährter Ideen, wie etwa des erfolgreichen Warcraft-III-Mods \"Defense of the Ancients\" (DotA), sondern auch die direkte Verpflichtung von Entwicklern, darunter Steve \"Guinsoo\" Feak, umfasste. Diese Vorgehensweise prädestinierte die interne Entwicklung eines eigenständigen Nachfolgers zu DotA."
            "\n\n"
            "Das Jahr 2008 markierte eine entscheidende Phase, in der Riot Games eine Partnerschaft mit Tencent Holdings einging, die den Weg für die Veröffentlichung von League of Legends in China ebnete. Diese Zusammenarbeit ermöglichte nicht nur eine globale Reichweite, sondern stellte auch die Implementierung des Free-to-Play-Modells in einem Markt mit bedeutenden Spielerzahlen sicher."
            "\n\n"
            "Die offizielle Einführung von League of Legends im Jahr 2009 zeichnete sich durch eine Auswahl von 40 Champions aus und setzte den Grundstein für eine konsistente Spielerbasis. Der Ansatz, das Spiel kontinuierlich durch regelmäßige Aktualisierungen und die Einführung neuer Champions zu pflegen, erwies sich als entscheidender Faktor für das anhaltende Wachstum."
            "\n\n"
            "Das Jahr 2014 markierte einen Wendepunkt mit 67 Millionen monatlich aktiven Nutzern. League of Legends etablierte sich nicht nur als führendes Esports-Spiel, sondern erfuhr auch eine kontinuierliche Ausweitung auf beeindruckende 115 Millionen monatliche Spieler bis zum aktuellen Stand 2023."
            "\n\n"
            "Die Expansion von Riot Games über die Grenzen von LoL hinaus manifestierte sich im Jahr 2020 mit der Einführung von Valorant, einem taktischen First-Person-Shooter, der Elemente von CS:GO mit einzigartigen Agentenfähigkeiten kombiniert. Die rasche Implementierung eines Esports-Turnierformats unterstreicht die Anpassungsfähigkeit des Studios."
            "\n\n"
            "Die laufenden Projekte, darunter das noch unbenannte Kampfspiel (Project L) und das Multiplayer-Spiel in Runeterra (Project F), reflektieren die fortgesetzte Diversifikation von Riot Games. Die Einführung von Riot Forge als Publishing-Division demonstriert darüber hinaus das Engagement für innovative Kooperationen mit kleineren Studios."
            "\n\n"
            "Die Historie von Riot Games illustriert somit die herausragende Erfolgsgeschichte eines visionären Studios, das durch eine konstante Ausrichtung auf die Spielercommunity, die gezielte Integration von Kreativität und die kontinuierliche Evolution seiner Produkte eine prominente Position in der dynamischen Landschaft der Spieleindustrie errungen hat. Riot Games fungiert somit als exemplarisches Modell eines \"spielerfokussierten\" Studios, dessen Ursprünge in einem konzeptionellen Dialog in den Räumlichkeiten der University of Southern California zu finden sind. [1][4]"
            "\n\n"
            "**Mission/Ziele:**\n"
            "Riot Games verfolgt seit seiner Gründung im Jahr 2006 das ambitionierte Ziel, der spielerorientierteste Entwickler der Welt zu sein. Die Grundphilosophie des Unternehmens besteht darin, die weltweit spielerfreundlichsten Spiele zu konzipieren, zu veröffentlichen und zu unterstützen. Dies wurde erstmals manifest, als im Jahr 2009 das bahnbrechende Spiel \"League of Legends\" das Licht der Welt erblickte und sich rasch zu einem der meistgespielten PC-Spiele weltweit entwickelte. Dieser Erfolg fungierte als Katalysator für das explosive Wachstum des E-Sports."
            "\n\n"
            "Mit dem Eintritt in die zweite Dekade von League of Legends setzt Riot Games nicht nur auf die kontinuierliche Weiterentwicklung dieses ikonischen Spiels, sondern diversifiziert auch sein Portfolio. Projekte wie Teamfight Tactics, Legends of Runeterra, VALORANT und League of Legends: Wild Rift sowie andere in der Entwicklung befindliche Spiele repräsentieren den Einsatz des Unternehmens, neue Spielerfahrungen zu schaffen. Die Initiative Riot Forge gewährt externen Entwicklern Zugang zu den reichen Welten von Riot, um Spiele wie \"Ruined King\" und andere Abenteuer in Runeterra zu gestalten."
            "\n\n"
            "Die Ausdehnung von Riot Games beschränkt sich nicht nur auf den digitalen Raum. Durch medienübergreifende Projekte in Musik, Comicbüchern, Brettspielen und der preisgekrönten animierten Serie \"Arcane\" wird die Welt von Runeterra auf vielfältige Weise erkundet und erweitert. [1]"
           "\n\n"
            "**Mitarbeiterzahl:**\n"
           "Gegenwärtig sind über 4.500 Mitarbeiter von Riot Games weltweit in mehr als 20 Niederlassungen tätig. [1]"
           "\n\n"
            "**Kontakt:**\n"
            "-https://www.riotgames.com/de/werde-rioter"
            "\n\n"
            "**Quellen:**\n"
            "-https://www.riotgames.com/de/wer-wir-sind [1]\n-https://www.riotgames.com/de/werde-rioter [2]\n-https://www.riotgames.com/de/werde-rioter/buros [3]\n-https://ftw.usatoday.com/lists/riot-games-history [4]")

IMAGE_NAME = "riotgames_logo.png"