# id:65

TITEL = "SAP"

CONTENT = (
    "## Beschreibung:\n"
    "Die SAP SE ist ein deutscher Softwarekonzern und einer der weltweit führenden Anbieter von Software für die "
    "Steuerung von Geschäftsprozessen [1]. Das Unternehmen wurde im April 1972 von den fünf ehemaligen "
    "IBM-Mitarbeitern Claus Wellenreuther, Hans-Werner Hector, Klaus Tschira, Dietmar Hopp und Hasso Plattner "
    "gegründet. Der Hauptsitz des Unternehmens befindet sich in Walldorf, Baden-Württemberg . SAP entwickelt "
    "Lösungen, die die effektive Datenverarbeitung und den Informationsfluss in Unternehmen erleichtern [1]. Die "
    "Produkte von SAP ermöglichen es Unternehmen, ihre Geschäftsprozesse zu optimieren und effizienter zu gestalten. "
    "Dazu gehören Bereiche wie Buchführung, Controlling, Vertrieb, Einkauf, Produktion, Lagerhaltung und "
    "Personalwesen [2].\n "
    "\n"
    "## Warum ist SAP für Informatiker interessant?:\n"
    "SAP ist ein global führender Anbieter von Unternehmenssoftware und bietet Informatikern eine breite Palette an "
    "Möglichkeiten, innovative Lösungen zu entwickeln und zu implementieren. Die Firma ermöglicht die Arbeit an "
    "komplexen Unternehmenslösungen, einschließlich Cloud-Technologien, Datenbanken und Analysewerkzeugen. Zudem "
    "bietet SAP vielfältige Karrierechancen und Einblicke in verschiedene Branchen.\n "
    "\n"
    "## Historie:\n"
    "Die Geschichte der SAP SE beginnt im Jahr 1972, als die fünf Unternehmer Dietmar Hopp, Hasso Plattner, "
    "Claus Wellenreuther, Klaus Tschira und Hans-Werner Hector eine Vision für das Geschäftspotenzial "
    "betriebswirtschaftlicher Software hatten. Mit einem Kunden und einer Handvoll Mitarbeiter schlug die SAP einen "
    "Weg ein, der nicht nur die Welt der IT, sondern auch die Art und Weise, in der Unternehmen ihre Geschäfte "
    "abwickeln, verändern sollte [3]. Seitdem hat sich SAP zu einem der weltweit führenden Anbieter von "
    "Business-Software entwickelt. Heute ist SAP das größte europäische (und außeramerikanische) sowie das weltweit "
    "drittgrößte Softwareunternehmen. Darüber hinaus handelt es sich bei SAP um das mit Abstand wertvollste "
    "börsennotierte deutsche Unternehmen [2].\n "
    "\n"
    "## Mission/Ziel:\n"
    "Die Mission von SAP ist es, Unternehmen dabei zu unterstützen, intelligente, nachhaltige Unternehmen zu werden ["
    "1] . SAP setzt sich dafür ein, die Abläufe in der weltweiten Wirtschaft und das Leben der Menschen zu "
    "verbessern. Das Ziel ist es, Unternehmen dabei zu unterstützen, intelligente, nachhaltige Unternehmen zu werden "
    "[2].\n "
    "\n"
    "**Website:**\n"
    "https://www.sap.com/\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "Ca. 111.961 Mitarbeiter weltweit [2].\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Ja\n"
    "\n"
    "**Kontakt:**\n"
    "https://jobs.sap.com/content/Studierende/?locale=de_DE\n"
    "\n"
    "**Quellen:**\n"
    "*-[Image] https://de.m.wikipedia.org/wiki/Datei:SAP-Logo.svg\n"
    "*-[1] https://www.sap.com/germany/about/company/history.html\n"
    "*-[2] https://de.wikipedia.org/wiki/SAP\n"
    "*-[3] https://www.heise.de/hintergrund/50-Jahre-SAP-Entwicklung-des-Unternehmens-von-1972-bis-heute-7062004.html\n"
)

IMAGE_NAME = "sap_logo.png"
