# id:6

TITEL = "Tesla"

CONTENT = (
"## Beschreibung:\n"
"Tesla, unter der Führung von Elon Musk, ist bekannt für Elektrofahrzeuge und erneuerbare Energien. Aktuell konzentriert sich Tesla auf die Massenproduktion von Elektroautos wie dem Model 3 und Model Y. Das Unternehmen expandiert weltweit mit Fabriken in verschiedenen Ländern, darunter Gigafactories in den USA, China und Deutschland. Tesla treibt auch die Entwicklung autonomer Fahrtechnologien voran.\n"
"\n"
"## Historie:\n"
"Tesla wurde 2003 gegründet und hat sich unter der Führung von Elon Musk zu einem führenden Unternehmen für Elektrofahrzeuge entwickelt. Die Modelle Roadster, Model S, Model X, Model 3 und Model Y trugen zu ihrem Erfolg bei. Tesla ist auch bekannt für Innovationen in erneuerbarer Energie, wie Gigafabriken für Batterien und Solardachprodukte. Elon Musk betonte Autopilot-Technologien und Over-the-Air-Updates. Trotz finanzieller Volatilität hat Tesla eine hohe Marktkapitalisierung erreicht.\n"
"\n"
"## Mission/Ziel:\n"
"Teslas Mission ist es eine möglichst große Auswahl an Elektrofahrzeugen zu produzieren die für alle zugänglich und erschwinglich sind.\n"
"\n"
"**Website:**\n"
"https://www.tesla.com/de_de\n"
"\n"
"**Mitarbeiterzahl:**\n"
"127.855 international (Stand 2022 ) \n "
"11.000 in Deutschland (Stand 2022)\n"
"\n"
"**Praxissemester/Praktikum:**\n"
"Ja\n"
"\n"
"**Kontakt:**\n"
"https://www.tesla.com/careers/search/?query=internship&site=DE\n"
"\n"
"**Quelen:**\n"
"*-https://www.tagesschau.de/wirtschaft/tesla-gruenheide-mitarbeiter-arbeitsbedingungen-100.html#:~:text=Der%20Autobauer%20verwies%20auf%20engmaschige,250.000%20Fahrzeuge%20im%20Jahr%20herstellen.\n"
"\n"
"*-https://de.wikipedia.org/wiki/Tesla,_Inc.\n"
"\n"
"*-https://blogmbh.de/unternehmensfuehrung/elon-musks-masterplan-tesla-vision-mission-und-strategie/5502/#:~:text=Musks%20Mission%20f%C3%BCr%20Tesla%20ist,alle%20zug%C3%A4nglich%20und%20erschwinglich%20sind%E2%80%9D.\n"
"\n"
"*-https://www.tesla.com/careers/search/?query=internship&site=DE\n"
"*-https://www.tesla.com/de_DE/careers/search/job/duales-studium-informatik-bsc-m-w-d-gigafactory-berlin-brandenburg-211562\n"
"*-https://www.tesla.com/\n"
)

IMAGE_NAME = "tesla.png"