# id:6

TITEL = "Tesla"

CONTENT = (
    "## Beschreibung:\n"
    "Tesla ist ein US-amerikanischer Automobilhersteller, der sich auf die Produktion von Elektroautos, "
    "Batteriespeichern und Photovoltaikanlagen spezialisiert hat . Das Unternehmen wurde im Jahr 2003 von Martin "
    "Eberhard und Marc Tarpenning gegründet und hat seinen Hauptsitz in Austin, Texas . Derzeit ist Elon Musk der CEO "
    "des Unternehmens . Aktuell arbeitet Tesla an der Entwicklung von selbstfahrenden Autos und hat bereits mehrere "
    "Modelle auf den Markt gebracht, die mit dem Autopiloten ausgestattet sind [1][3]. Das Unternehmen hat auch "
    "Pläne, in Zukunft autonome Taxis anzubieten [3]. Tesla hat in den letzten Jahren mehrere Meilensteine erreicht. "
    "Im Jahr 2008 brachte das Unternehmen den weltweit ersten elektrischen Serienwagen mit einem Batteriesystem aus "
    "Lithium-Ionen-Zellen auf den Markt, den Tesla Roadster [5][1]. Im Jahr 2012 brachte Tesla das Model S auf den "
    "Markt, eine Oberklasse-Limousine, die in der Lage ist, bis zu 402 Meilen mit einer einzigen Ladung zurückzulegen "
    "[6][1]. Im Jahr 2015 brachte Tesla die Powerwall auf den Markt, einen Batteriespeicher für den Heimgebrauch [7]["
    "1]. Im Jahr 2017 brachte Tesla das Model 3 auf den Markt, eine Mittelklasse-Limousine, die für den Massenmarkt "
    "konzipiert ist [1][2]. Im Jahr 2020 hat Tesla den Cybertruck vorgestellt, einen futuristischen Pickup-Truck, "
    "der mit einer einzigen Ladung bis zu 500 Meilen zurücklegen kann [3].\n "
    "\n"
    "## Warum ist Tesla für Informatiker interessant?:\n"
    "Die Firma Tesla bietet für Informatiker spannende Möglichkeiten in der Entwicklung von Elektrofahrzeugen, "
    "erneuerbaren Energietechnologien und künstlicher Intelligenz. Informatiker haben hier die Chance, innovative "
    "Software- und Hardwarelösungen für Fahrzeuge und autonomes Fahren zu gestalten sowie an wegweisenden Projekten "
    "im Bereich der Mobilität mitzuwirken.\n "
    "\n"
    "## Historie:\n"
    "Tesla wurde im Jahr 2003 von Martin Eberhard und Marc Tarpenning gegründet [1][2][3]. Das Unternehmen hat seinen "
    "Ursprung in der Idee, ein Elektroauto zu bauen, das den Benzin-betriebenen Autos in nichts nachsteht [4]. Im "
    "Jahr 2008 brachte Tesla den weltweit ersten elektrischen Serienwagen mit einem Batteriesystem aus "
    "Lithium-Ionen-Zellen auf den Markt, den Tesla Roadster [5][1]. Im Jahr 2012 brachte Tesla das Model S auf den "
    "Markt, eine Oberklasse-Limousine, die in der Lage ist, bis zu 402 Meilen mit einer einzigen Ladung zurückzulegen "
    "[6][1]. Im Jahr 2015 brachte Tesla die Powerwall auf den Markt, einen Batteriespeicher für den Heimgebrauch [7]["
    "1]. Im Jahr 2017 brachte Tesla das Model 3 auf den Markt, eine Mittelklasse-Limousine, die für den Massenmarkt "
    "konzipiert ist [1][2]. Im Jahr 2020 hat Tesla den Cybertruck vorgestellt, einen futuristischen Pickup-Truck, "
    "der mit einer einzigen Ladung bis zu 500 Meilen zurücklegen kann [3].\n "
    "\n"
    "## Mission/Ziel:\n"
    "\"Seit der Unternehmensgründung im Jahr 2003 verfolgt Tesla das Ziel, die Umstellung der Welt auf nachhaltige "
    "Energie zu beschleunigen.\"[6]\n "
    "\n"
    "**Website:**\n"
    "https://www.tesla.com/de_de\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "127.855 international (Stand 2022 ) \n "
    "11.000 in Deutschland (Stand 2022)\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Ja\n"
    "\n"
    "**Kontakt:**\n"
    "https://www.tesla.com/careers/search/?query=internship&site=DE\n"
    "\n"
    "**Quellen:**\n"
    "*-[Image] https://en.wikipedia.org/wiki/File:Tesla_logo.png\n"
    "*-[1] https://de.wikipedia.org/wiki/Tesla,_Inc\n"
    "*-[2] https://www.msn.com/de-de/finanzen/top-stories/teslas-wachstumsziel-wohl-zu-hoch-angesetzt-teslas-ir-chef"
    "-martin-viecha-sieht-tesla-in-wachstumsdelle/ar-AA1kztg6\n "
    "*-[3] https://www.suedkurier.de/ueberregional/rundblick/tesla-elon-musk-gruendung-geschichte-historie-infos"
    "-hintergrund\n "
    "*-[4] https://teslamag.de/\n"
    "*-[5] The Verge\n"
    "*-[6] https://www.tesla.com/de_de/elon-musk#:~:text=Seit%20der%20Unternehmensgr%C3%BCndung%20im%20Jahr,"
    "auf%20nachhaltige%20Energie%20zu%20beschleunigen.\n "
    "\n"

)

IMAGE_NAME = "tesla.png"
