# id:61

TITEL = "Volkswagen"

CONTENT = (
"## Beschreibung:\n"
"Die Volkswagen Aktiengesellschaft (VW AG) ist ein deutscher Automobilhersteller mit Sitz in Wolfsburg, Niedersachsen. Sie wurde am 28. Mai 1937 gegründet und gehört zu den größten Automobilherstellern der Welt. Die VW AG wird indirekt mehrheitlich von den österreichischen Familien Porsche und Piëch kontrolliert [1]. Das Unternehmen produziert eine Vielzahl von Fahrzeugen, von Kleinwagen bis hin zu Luxusfahrzeugen und Nutzfahrzeugen. Die VW AG agiert als Muttergesellschaft der Fahrzeugmarke Volkswagen Pkw sowie der Tochtergesellschaften Seat, Škoda Auto und Audi sowie der Luxusmarken Bentley, Ducati (Motorräder), Lamborghini und Porsche[1].\n"
"\n"
"## Historie:\n"
"Die Geschichte der Volkswagen AG beginnt mit dem Käfer, der ab 1934 als Vorzeigeprojekt des deutschen NS-Staates entwickelt wird [2]. Am 28. Mai 1937 wurde das Unternehmen als Gesellschaft zur Vorbereitung des Deutschen Volkswagens mbH formal gegründet und errichtete 1938 in Wolfsburg sein Hauptwerk. Nach dem Zweiten Weltkrieg begann auf britischen Befehl Ende 1945 die Serienfertigung der Volkswagen Limousine. Mit den Modellen Typ 1 (Käfer) und ab 1950 dem Typ 2 (Transporter) wurde Volkswagen weltweit zu einem der bekanntesten Symbole des deutschen Wirtschaftswunders. In den 1970er Jahren hielten innovative und flexible Fertigungssysteme Einzug und führten zur Etablierung einer neuen Volkswagen Generation mit den Modellen Passat, Scirocco, Golf und Polo [2].\n"
"\n"
"## Mission/Ziel:\n"
"Mit der neuen Konzernstrategie „NEW AUTO“ – Mobility for generations to come will die Volkswagen AG sich auf die globalen Veränderungen der Mobilität vorbereiten und damit die Transformation von Volkswagen in ein softwarezentriertes Unternehmen maßgeblich vorantreiben [3]. Die VW AG hat sich zum Ziel gesetzt, bis 2050 ein bilanziell CO2-neutrales Unternehmen zu werden [3].\n"
"\n"
"**Website:**\n"
"https://www.volkswagen.de/de.html\n"
"\n"
"**Mitarbeiterzahl:**\n"
"Im Jahr 2022 etwa 676.000 Mitarbeiter [4].\n"
"\n"
"**Praxissemester/Praktikum:**\n"
"Ja\n"
"\n"
"**Kontakt:**\n"
"https://www.volkswagen-karriere.de/de/einstiegsmoeglichkeiten/studenten/klassisches-praktikum.html\n"
"\n"
"**Quellen:**\n"
"*-[Image] https://de.m.wikipedia.org/wiki/Datei:Volkswagen_logo_2019.svg\n"
"*-[1] https://www.volkswagen-newsroom.com/de/geschichte-3693\n"
"*-[2] https://de.wikipedia.org/wiki/Volkswagen_AG\n"
"*-[3] https://www.volkswagen-group.com/de/historie-15914\n"
"*-[4] https://www.volkswagen-group.com/de/unternehmen-15765\n"
)

IMAGE_NAME = "volkswagen_logo.png"