TITEL = "MediaAndEntertainment"

CONTENT = (
    "## Beschreibung:\n"
    "Text 1\n"
    "\n"
    "## Warum ist <Unternehmen> für Informatiker interessant?:\n"
    "Text 2\n"
    "\n"
    "## Historie:\n"
    "Text 2\n"
    "\n"
    "## Mission/Ziel:\n"
    "Text 3\n"
    "\n"
    "**Website:**\n"
    "Text 4\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "Text 5\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Ja/Nein\n"
    "\n"
    "**Kontakt:**\n"
    "Text 6\n"
    "\n"
    "**Quellen:**\n"
    "*-[Image]https://www.freepik.com/free-vector/characters-people-holding-multimedia-icons-illustration_3046749.htm# \n Image by rawpixel.com on Freepik\n""
    "\n  Image by pch.vector on Freepik \n"
    "*-[1] www.....\n"
    "*-[2] www.....\n"
)
IMAGE_NAME = "mediaandentertainment_logo.png"