TITEL = "Gesundheitswesen"

CONTENT = (
    "## Beschreibung:\n"
    "Text 1\n"
    "\n"
    "## Warum ist <Unternehmen> für Informatiker interessant?:\n"
    "Text 2\n"
    "\n"
    "## Historie:\n"
    "Text 2\n"
    "\n"
    "## Mission/Ziel:\n"
    "Text 3\n"
    "\n"
    "**Website:**\n"
    "Text 4\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "Text 5\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Ja/Nein\n"
    "\n"
    "**Kontakt:**\n"
    "Text 6\n"
    "\n"
    "**Quellen:**\n"
    "*-[Image]https://www.freepik.com/free-vector/tiny-pharmacist-with-pills-vitamins-flat-vector-illustration-doctors-writing-prescriptions-antibiotics-working-together-helping-patients-cure-pharmacy-business-drugstore-concept_24644990.htm#\n"
    "*-[1] www.....\n"
    "*-[2] www.....\n"
)

IMAGE_NAME = "pharmaceuticalsandhealth_logo.png"

