# id:59
TITEL = "Boeing"

CONTENT = (
    "## Beschreibung:\n"
    "Boeing ist ein führendes globales Luft- und Raumfahrtunternehmen, das kommerzielle Flugzeuge, "
    "Verteidigungsprodukte und Weltraumsysteme für Kunden in mehr als 150 Ländern entwickelt, herstellt und wartet ["
    "4]. Als einer der größten US-Exporteure nutzt das Unternehmen die Talente einer globalen Lieferantenbasis, "
    "um wirtschaftliche Chancen, Nachhaltigkeit und gesellschaftliche Auswirkungen voranzutreiben [4]. Die "
    "Geschäftseinheiten von Boeing sind um drei Hauptgruppen von Produkten und Dienstleistungen organisiert - "
    "kommerzielle Flugzeuge, Militärflugzeuge und Raketen sowie Raumfahrt und Kommunikation [1]. Boeing stellt sieben "
    "verschiedene Familien von Verkehrsflugzeugen her, die in zwei Einrichtungen - Renton und Everett - im "
    "Bundesstaat Washington montiert werden [1].\n "
    "\n"
    "## Warum ist Boeing für Informatiker interessant?:\n"
    "Boeing bietet Informatikern eine faszinierende Arbeitsumgebung in der Luft- und Raumfahrtindustrie. Hier haben "
    "sie die Chance, an wegweisenden Projekten mitzuarbeiten, angefangen bei der Flugzeugentwicklung bis hin zu "
    "Raumfahrtmissionen. Die Bandbreite der Möglichkeiten umfasst die Entwicklung von Flugsteuerungssystemen, "
    "Datenanalyse für Flugzeugwartung, Raumfahrtsoftware und andere innovative Technologien. Dies ermöglicht "
    "Informatikern, an entscheidenden Technologien und Lösungen für die Luft- und Raumfahrtbranche mitzuwirken und "
    "macht Boeing zu einem attraktiven Arbeitsplatz für Technologieexperten.\n "
    "\n"
    "## Historie:\n"
    "Die Boeing Company wurde 1916 von dem amerikanischen Holzhändler William E. Boeing gegründet [1] [2]. Boeing "
    "gründete das Unternehmen kurz nachdem er und der US-Marineoffizier Conrad Westervelt ein einmotoriges, "
    "zweisitziges Wasserflugzeug, das B&W, entwickelt hatten. Im Jahr 1917 wurde das Unternehmen in Boeing Airplane "
    "Company umbenannt1. Während des Ersten Weltkriegs baute das Unternehmen “Flugboote” für die Marine [1]. Im Jahr "
    "1916 begann Boeing mit der Produktion von Flugzeugen, was zum ersten Flug des Model 1 führte [3]. Im Laufe der "
    "Jahre hat Boeing eine Reihe von Meilensteinen erreicht. Im Jahr 1930 baute Boeing den Monomail, "
    "ein Ganzmetall-Monoplan, der Post beförderte [2].\n "
    "\n"
    "## Mission/Ziel:\n"
    "Die Mission von Boeing ist es, die Welt durch Innovation und Technologie zu verbinden. Das Unternehmen strebt "
    "danach, die Luftfahrtindustrie durch die Entwicklung von fortschrittlichen Technologien und Produkten zu "
    "revolutionieren, die die Sicherheit, Effizienz und Nachhaltigkeit des Fliegens verbessern. Boeing hat auch eine "
    "starke Verpflichtung zur Nachhaltigkeit und arbeitet daran, seine Produkte und Prozesse umweltfreundlicher zu "
    "gestalten.\n "
    "\n"
    "**Website:**\n"
    "https://www.boeing.de/\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "156.000 (2022)\n"
    "\n"
    "**Quellen:**\n"
    "*-[Image] https://freebiesupply.com/logos/boeing-logo/\n"
    "*-[1] https://www.boeing.com/history\n"
    "*-[2] https://en.wikipedia.org/wiki/History_of_Boeing\n"
    "*-[3] https://simpleflying.com/boeing-history/\n"
    "*-[4] https://www.britannica.com/topic/Boeing-Company\n"
    "*-[5] https://www.boeing.com/company/\n"
    "\n"
)

IMAGE_NAME = "boeing.png"
