# id:26

TITEL = "ESL Gaming GmbH"

CONTENT = (
    "## Beschreibung:\n"
    "Die ESL Gaming GmbH ist ein Unternehmen welches sich auf das austragen von der sogenannten \"Electronic Sports League\"\n"
    "fokussiert.\n Sie ist einer der Spitzenreiter in diesem Gebiet und hat mit Positionen in 6 Kontinenten eine\n"
    " Vielfältige Kultur.\n"
    "## Warum ist die ESL Gaming GmbH für Informatiker interessant?:\n"
    "Die ESL Gaming GmbH ist eines der größten Esports Unternehmen und ermöglicht so in der Arbeit\n"
    "Verschiedene Aspekte des Esports mitzuerleben. \n Außerdem bietet ESL Gaming viele verschiedene Jobs in "
    "verschiedenen Ländern, welche einem Flexibilität bieten kann.\n"
    "\n"
    "## Historie:\n"
    "ESL Gaming GmbH wurde im Jahre 2000 in Köln gegründet. Sie veranstaltet Turniere mit Geldpreisen.\n"
    "\n"
    "## Mission/Ziel:\n"
    "Die ESL Gaming GmbH setzt es als Ziel das jeder \"from Zero to Hero\" gehen kann und so \n"
    "Die selben Chancen hat.\n Ihre GGFORALL Initiative soll für eine sichere Umgebung für Frauen in Esports sorgen.\n"
    "\n"
    "**Website:**\n"
    "esl.com\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "900+\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Nein\n"
    "\n"
    "**Kontakt:**\n"
    "https://play.eslgaming.com/contact\n"
    "\n"
    "**Quellen:**\n"
    "*-[Image] https://eslfaceitgroup.com/wp-content/uploads/2021/10/ESL_Logo_Horizontal_RGB_POS.png\n"
    "*-[1] https://eslfaceitgroup.com/\n"
    "*-[2] https://en.wikipedia.org/wiki/ESL_(company)\n"
    "*-[3] https://esl.com"
    "*-[4] https://repositorio.iscte-iul.pt/handle/10071/20783\n"
)

IMAGE_NAME = "eslgaming_logo.png"
