# id:18

TITEL = "HDI SE"

CONTENT = (
    "## Beschreibung:\n"
    "Die HDI SE ist in über 130 Ländern aktiv, sowohl über Tochtergesellschaften als auch durch ein Netzwerk von "
    "Partnern. Mit einem professionellen Schadenmanagement auf nationaler und internationaler Ebene positioniert sich "
    "HDI als zuverlässiger Partner in der Industrieversicherung. Das Schadenmanagement von HDI Global SE ist "
    "dezentral organisiert, wobei Niederlassungen bundesweit und lokale HDI Gesellschaften bzw. Netzwerkpartner "
    "international involviert sind. Bei Großschäden übernimmt das zentrale Schadenmanagement die Federführung, "
    "um eine effiziente Abstimmung zwischen den Schadenexperten im In- und Ausland sicherzustellen. Die oberste "
    "Priorität liegt dabei auf der Begrenzung des Schadenausmaßes und der Vermeidung von kundenbedingten Verlusten, "
    "um die Zukunftsfähigkeit des Unternehmens zu gewährleisten. HDI Global SE unterstützt Unternehmen bei der "
    "Identifizierung und Minimierung von Risiken im Geschäftsalltag durch HDI Risk Consulting (HRC). Die Experten von "
    "HRC erarbeiten gemeinsam mit den Kunden geeignete Maßnahmen, um Notfälle zu verhindern und die betriebliche "
    "Resilienz zu stärken. Digitale Tools wie die HDI Remote App ermöglichen ortsunabhängige virtuelle "
    "Besichtigungen, während die Webapplikation GREEN 4.0 Flexibilität bietet, um standortbezogene Risiken "
    "bedarfsgerecht zu verwalten. HDI Global SE versteht sich als vertrauensvoller Partner für Mittelständler, "
    "Industrie-Unternehmen und Konzerne weltweit. Das Unternehmen entwickelt maßgeschneiderte Versicherungslösungen, "
    "indem es den Betrieb seiner Kunden genau kennenlernt und versteht. Mit hohen Deckungskapazitäten bietet HDI "
    "außerordentliche Flexibilität in Industrieversicherungen, die auf der sorgfältigen Einschätzung täglich "
    "wechselnder Anforderungen durch erfahrene Experten basieren. Für Vertriebspartner bietet HDI Global SE "
    "umfangreiche Unterstützung und einen ausgezeichneten Service. Die Partnerschaft zielt darauf ab, den Erfolg der "
    "Partner im täglichen Geschäft zu maximieren und einen erstklassigen Service zu gewährleisten, der den hohen "
    "Standards entspricht, die auch die Kunden von HDI Global SE gewohnt sind.[1]\n "
    "\n"

    "## Historie:\n"
    "Die Historie des HDI-Konzerns erstreckt sich über mehr als ein Jahrhundert und spiegelt eine bemerkenswerte "
    "Entwicklung von einem spezialisierten Haftpflichtversicherer für die deutsche Industrie zu einem internationalen "
    "Versicherungskonzern wider. Im Jahr 1903 wurde der Grundstein für das Unternehmen mit der Gründung des "
    "\"Haftpflichtverbandes der deutschen Eisen- und Stahlindustrie\" gelegt. Dieser entstand aus der Unzufriedenheit "
    "über die deutlichen Unterschiede zwischen den Prämienzahlungen und -leistungen. Sechs Berufsgenossenschaften und "
    "176 Unternehmen der Eisen- und Stahlindustrie schlossen sich zusammen, um einen industrieeigenen "
    "Versicherungsverein auf Gegenseitigkeit zu schaffen. Die Jahre vergingen, und 1924 erfolgte eine wichtige "
    "Kooperation mit dem Gerling-Konzern, der die Rückversicherung für HDI übernahm. Ursprünglich als hausnaher "
    "Sachversicherer konzipiert, wurde der Verband schrittweise in eine reine Rückversicherungsgesellschaft "
    "umgewandelt. Nach dem Zweiten Weltkrieg, im Jahr 1952, löste sich HDI von den Berufsgenossenschaften, "
    "um einen breiteren Kundenkreis anzusprechen. Eine neue Satzung wurde eingeführt, und der Haftpflichtverband "
    "öffnete sich für Unternehmen aus allen Branchen. In den 1970er Jahren fusionierte HDI mit dem "
    "Feuerschadenverband rheinisch-westfälischer Zechen und änderte seinen Namen 1976 in „Haftpflichtverband der "
    "Deutschen Industrie V.a.G“ (HDI). Der Konzern wuchs in den folgenden Jahren auf über 20 Gesellschaften im In- "
    "und Ausland. Die 1990er Jahre brachten einen weiteren Wandel mit sich. Aufgrund der risikoexponierten "
    "Geschäftsfelder und des starken Zuwachses in der Rückversicherung erfolgte eine Umstrukturierung hin zu einer "
    "ausbalancierten Risikoverteilung. Ein ausgewogener Mix zwischen Industrie-, Privatkunden- und "
    "Rückversicherungsgeschäft wurde eingeführt, und die vertriebliche Orientierung wurde auf chancenreiche "
    "Geschäftsfelder ausgerichtet. Im Jahr 2003 entstand aus dem HDI-Konzern die Talanx-Gruppe, die eine verstärkte "
    "Internationalisierung vorantrieb. Die Eingliederung der Gerling-Gruppe erfolgte 2005. In der Privat- und "
    "Firmenversicherung wurden die Marken HDI und HDI-Gerling im September 2012 unter der „neuen alten Marke“ HDI "
    "zusammengefasst. Im selben Jahr ging die Talanx AG erfolgreich an die Börse. Seit 2016 wird der Geschäftsbereich "
    "Industrieversicherung durch die HDI Global SE geführt. Diese Entwicklungen zeugen von der kontinuierlichen "
    "Anpassung des Unternehmens an die sich verändernden Anforderungen und Chancen auf dem Versicherungsmarkt im "
    "Laufe der Zeit.[2]\n "
    "\n"

    "## Mission/Ziel:\n"
    "Das Ziel des HDI Konzerns besteht darin, ein verlässlicher und führender Partner für Versicherungslösungen zu "
    "sein, der die individuellen Bedürfnisse seiner Kunden erfüllt. Als Versicherungsgruppe strebt HDI danach, "
    "umfassenden Schutz und finanzielle Sicherheit anzubieten. Dabei legt das Unternehmen großen Wert auf Innovation, "
    "Kundenzufriedenheit und nachhaltige Geschäftspraktiken. HDI verfolgt das Ziel, Risiken verantwortungsbewusst zu "
    "managen und erstklassige Dienstleistungen anzubieten, um den langfristigen Erfolg seiner Kunden zu sichern.[1] ["
    "3]\n "
    "\n"

    "**Website:**\n"
    "https://www.hdi.global/de-de/\n"
    "\n"

    "**Mitarbeiterzahl:**\n"
    "Die HDI Group hat Weltweit 24000 Mitarbeiter.[4]\n"
    "\n"

    "**Quelle:**\n"
    "-[1]https://www.hdi.global/de-de/\n"
    "-[2]https://www.hdi.global/de-de/das-unternehmen/ueber-uns/\n"
    "-[3]https://www.hdi.de/ueber-uns/unternehmen/information-gem-der-verordnung-ueber-nachhaltigkeitsbezogene"
    "-offenlegungspflichten-im-finanzdienstleistungssektor/\n "
    "-[4] https://careers.hdi.group/de/hdi_group_als_arbeitgeber\n"
    "-Bild: https://ecda.eur.nl/2021/02/23/we-are-pleased-to-announce-that-hdi-global-specialty-se-is-our-new"
    "-corporate-partner-as-of-1-january-2021/")

IMAGE_NAME = "hdi_logo.png"
