# id:40

TITEL = "Lidl"

CONTENT = ("## Beschreibung:\n"
           "Lidl, als nachhaltiger Frische-Discounter, steht für höchste Qualität zum besten Preis und bietet ein "
           "schnelles, einfaches sowie zuverlässiges Einkaufserlebnis. Die Unternehmensphilosophie betont Fairness, "
           "Kommunikation auf Augenhöhe und das Streben danach, jederzeit die erste Wahl für Kunden, Mitarbeiter und "
           "Partner zu sein. Das Geschäft wird systematisch, einfach und unkompliziert betrieben, wodurch Lidl ein "
           "herausragendes Preis-Leistungsverhältnis bietet. Als hybride Marke ist Lidl nah am Kunden und kombiniert "
           "ein umfangreiches Food- und Non-Food-Sortiment sowohl online als auch in stationären Geschäften. "
           "Das Unternehmen handelt bewusst im Sinne von Mensch und Natur und setzt sich kontinuierlich für "
           "Verbesserungen in den Bereichen Umwelt- und Klimaschutz, Mitarbeiter, gesellschaftliches Engagement und "
           "Sortiment ein. Der Erfolg von Lidl basiert auf dem unermüdlichen Engagement aller Mitarbeiter, "
           "die gemäß dem Motto \"Lidl muss man können\" täglich daran arbeiten, das zentrale Versprechen \"Lidl "
           "lohnt sich\" einzulösen. [1]\n "
           "\n"

           "## Warum ist Lidl für Informatiker interessant?:\n"
           "Lidl ist für Informatiker eine attraktive Arbeitsumgebung aufgrund seiner innovativen digitalen "
           "Strategien und dem kontinuierlichen Streben nach technologischer Exzellenz. Das Unternehmen investiert "
           "stark in digitale Lösungen, um seine Geschäftsprozesse zu optimieren, was Informatikern die Möglichkeit "
           "bietet, an anspruchsvollen Projekten teilzunehmen. Die offene Unternehmenskultur fördert den Austausch "
           "von Ideen und ermöglicht es IT-Experten, kreativ an der Entwicklung und Implementierung neuer "
           "Technologien mitzuwirken. Durch die vielfältigen Herausforderungen im Bereich E-Commerce, Logistik und "
           "Datenmanagement bietet Lidl Informatikern eine spannende berufliche Perspektive.\n "
           "\n"

           "## Historie:\n"
           "Die Historie von Lidl begann im baden-württembergischen Neckarsulm, wo in den 1930er Jahren die Lidl & "
           "Schwarz KG als Lebensmittel-Sortimentsgroßhandlung gegründet wurde. Dies legte den Grundstein für die "
           "spätere internationale Expansion des Unternehmens. Ein herausragendes Merkmal in der Geschichte von Lidl "
           "ist der stetige Mut, neue Wege zu gehen und Impulse für die gesamte Branche zu setzen.\n\n "
           "Durch das erfolgreiche Discount-Prinzip konnte Lidl rasch wachsen, und bereits nach 15 Jahren existierten "
           "über 450 Filialen in Deutschland. In den späten 1980er Jahren begann die Expansion in andere Länder. "
           "Heute betreibt Lidl in 31 Ländern weltweit über 12.200 Filialen und setzt weiterhin auf Wachstum. Seit "
           "2017 und 2018 ist Lidl auch in den USA und in Serbien mit eigenen Filialen vertreten.\n "
           "\n"
           "Die Erfolgsgeschichte von Lidl zeigt Meilensteine wie die Einführung des Pfandsystems für Einwegflaschen "
           "im Jahr 2002 und die Integration einer eigenen Fairtrade-Marke namens \"Fairglobe\" im Jahr 2006. Der "
           "Lidl-Onlineshop ging 2008 an den Start, und 2017 wagte das Unternehmen den Sprung über den Atlantik, "
           "indem es die ersten Filialen in den Vereinigten Staaten eröffnete. In den folgenden Jahren wurde Lidl "
           "mehrfach für sein nachhaltiges Engagement ausgezeichnet, unter anderem mit dem Fairtrade-Award im Jahr "
           "2016. Die kontinuierliche Weiterentwicklung zeigt sich auch in der Veröffentlichung des ersten "
           "Nachhaltigkeitsberichts nach internationalem GRI-Standard im Jahr 2018 und der Kooperation mit Bioland im "
           "gleichen Jahr. Im Jahr 2019 veröffentlichte Lidl seine Nachhaltigkeitsstrategie 2030, die das Engagement "
           "des Unternehmens für eine nachhaltige Zukunft unterstreicht. [2]\n "
           "\n"

           "## Mission/Ziele:\n"
           "Lidl verfolgt eine klare Vision von Verantwortung und Nachhaltigkeit, die sich in dem Leitgedanken \"Auf "
           "dem Weg nach morgen\" manifestiert. Das Unternehmen sieht es als seine Pflicht an, Verantwortung zu "
           "übernehmen, insbesondere dort, wo sein Handeln Auswirkungen auf Mensch und Umwelt hat. Das tägliche "
           "Streben nach Erfüllung des Qualitätsversprechens steht dabei im Mittelpunkt. "
           "\n\n"
           "Die Ziele von Lidl sind darauf ausgerichtet, die gesamte Wertschöpfungskette in den Blick zu nehmen und "
           "das Unternehmen fit für eine nachhaltige Zukunft zu machen. Dabei steht eine Vision im Fokus: Das "
           "nachhaltigste Sortiment zum besten Preis anzubieten. Die Grundhaltung \"Gut für den Planeten\", "
           "\"Gut für die Menschen\" und \"Gut für dich\" verdeutlicht diese Zielsetzung. "
           "\n\n"
           "Sechs Fokusthemen, darunter \"Biodiversität achten\", \"Klima schützen\", \"Ressourcen schonen\", "
           "\"Fair handeln\", \"Gesundheit fördern\" und \"Dialog führen\", werden aktiv in die Tat umgesetzt, "
           "sowohl auf regionaler als auch globaler Ebene. Lidl engagiert sich dabei transparent und mit großem "
           "Einsatz. "
           "\n\n"
           "Die Überzeugung von Lidl liegt darin, dass unternehmerischer Erfolg langfristig nur im Einklang mit der "
           "Achtung von Menschenrechten und Umweltstandards möglich ist. Daher übernimmt das Unternehmen seine "
           "unternehmerische Verantwortung ernst, indem es einen risikobasierten Managementansatz verfolgt, "
           "um menschenrechtliche und umweltbezogene Risiken zu identifizieren, präventive Maßnahmen zu ergreifen und "
           "im Falle des Eintritts von Risiken angemessene Korrekturmaßnahmen zu ergreifen. "
           "\n\n"
           "#Aufgrund der Vielfältigkeit der Geschäftstätigkeit und der komplexen internationalen Lieferketten setzt "
           "Lidl auf verschiedene Meldekanäle, über die Hinweise auf Verletzungen von Menschenrechts- oder "
           "Umweltpflichten gemeldet werden können. Damit stellt das Unternehmen sicher, auch in komplexen "
           "Situationen seiner unternehmerischen Sorgfaltspflicht nachzukommen. [3] "
           "\n\n"

           "## Website:\n"
           "https://www.lidl.de\n"
           "\n"

           "## Mitarbeiterzahl:\n"
           "Täglich gewährleisten mehr als 100.000 Mitarbeiter in über 3.250 Filialen in Deutschland die "
           "Zufriedenheit der Kunden. [1]\n "
           "\n"

           "## Kontakt:\n"
           "- https://jobs.lidl.de\n"
           "\n"

           "## Quellen:\n"
           "-[Bild] https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Lidl-Logo.svg/2048px-Lidl-Logo.svg.png"
           "\n-https://unternehmen.lidl.de [1]\n-https://unternehmen.lidl.de/ueber-lidl/geschichte ["
           "2]\n-https://unternehmen.lidl.de/verantwortung/nachhaltigkeitsmanagement [3]")

IMAGE_NAME = "lidl_logo.png"
