# id:3

TITEL = "Microsoft"

CONTENT = (
    "## Beschreibung:\n"
    "Heute ist Microsoft ein multinationales Technologieunternehmen, das eine breite Palette von Softwareprodukten "
    "und Dienstleistungen entwickelt und vermarktet [1][3]. Zu den bekanntesten Softwareprodukten von Microsoft "
    "gehören das Betriebssystem Microsoft Windows, die Produktivitätssoftware Microsoft Office, der Webbrowser Edge "
    "und die Suchmaschine Bing[1][4]. Darüber hinaus bietet Microsoft Cloud-Dienste über seine Azure-Plattform an13. "
    "Microsoft hat auch Hardwareprodukte entwickelt und verkauft, darunter die Xbox-Spielekonsole und die "
    "Surface-Tablets [3]. Microsoft hat Büros in mehr als 100 Ländern und bietet seine Produkte und Dienstleistungen "
    "weltweit an [3].\n "
    "\n"
    "## Warum ist Microsoft für Informatiker interessant?:\n"
    "Microsoft ist für Informatiker aufgrund seiner vielfältigen Technologien und Dienstleistungen in Bereichen wie "
    "Cloud-Computing, künstliche Intelligenz und Betriebssysteme attraktiv. Es bietet zahlreiche Möglichkeiten für "
    "Softwareentwicklung, Forschung und Innovation, beispielsweise in der Entwicklung von Windows-Betriebssystemen, "
    "Cloud-Services wie Azure und künstlicher Intelligenz mit Produkten wie Microsoft 365. Die Innovationschancen, "
    "die Vielfalt der Projekte und die Unternehmensgröße machen Microsoft zu einem äußerst interessanten Arbeitsplatz "
    "für Informatiker.\n "
    "\n"
    "## Historie:\n"
    "Microsoft wurde am 4. April 1975 von Bill Gates und Paul Allen in Albuquerque, New Mexico, gegründet [1][2]. "
    "Ursprünglich konzentrierte sich das Unternehmen auf die Entwicklung eines BASIC-Interpreters für den Altair "
    "8800, einen frühen Personalcomputer [1]. Im Jahr 1980 bildete Microsoft eine Partnerschaft mit IBM, "
    "um das Betriebssystem von Microsoft auf IBM-Computern zu bündeln. Im Jahr 1985 bat IBM Microsoft, "
    "ein neues Betriebssystem für ihre Computer namens OS/2 zu entwickeln. Microsoft produzierte dieses "
    "Betriebssystem, verkaufte aber auch weiterhin seine eigene Alternative, die sich als direkte Konkurrenz zu OS/2 "
    "erwies. Microsoft Windows überflügelte schließlich OS/2 in Bezug auf den Verkauf. Als Microsoft in den 1990er "
    "Jahren mehrere Versionen von Microsoft Windows auf den Markt brachte, hatte es über 90% Marktanteil an den "
    "weltweiten Personalcomputern erobert [1].\n "
    "\n"
    "## Mission/Ziel:\n"
    "Die Mission von Microsoft ist es, jede Person und jedes Unternehmen auf dem Planeten zu befähigen, "
    "mehr zu erreichen. Diese Mission zeigt, dass das Unternehmen sich darauf konzentriert, Menschen und "
    "Organisationen durch seine Informationstechnologieprodukte und -dienstleistungen zu befähigen [5][6].\n "
    "\n"
    "**Website:**\n"
    "https://www.microsoft.com/de-de\n"
    "https://careers.microsoft.com/v2/global/en/home.html\n"
    "https://www.microsoft.com/de-de/about\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "Zum 30. Juni 2023 beschäftigte Microsoft weltweit etwa 221.000 Mitarbeiter [7] [4].\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Ja\n"
    "\n"
    "**Kontakt:**\n"
    "https://careers.microsoft.com/v2/global/en/home.html\n"
    "\n"
    "**Quellen:**\n"
    "*-[Image] https://inoya.de/partnerschaften/microsoft/microsoft-365/\n"
    "*-[1] https://en.wikipedia.org/wiki/History_of_Microsoft\n"
    "*-[2] https://www.britannica.com/topic/Microsoft-Corporation\n"
    "*-[3] https://www.thoughtco.com/microsoft-history-of-a-computing-giant-1991140\n"
    "*-[4] https://www.microsoft.com/de-de/about\n"
    "*-[5] https://www.microsoft.com/investor/reports/ar12/financial-review/business-description/index.html\n"
    "*-[6] https://en.wikipedia.org/wiki/Microsoft\n"
    "*-[7] https://content.dsp.co.uk/a-brief-history-of-microsoft-the-worlds-biggest-software-company\n"
)

IMAGE_NAME = "microsoft.png"
