# id:29

TITEL = "Netcologne"

CONTENT = (
    "## Beschreibung:\n"
    "Netcologne ist ein Internetanbieter und sie sind Vorreiter in Deutschland im Glasfaserausbau.\n"
    "Sie haben über 29.000 Kilometer an verlegtem Kabel und sind im Ausbau.\n"
    "## Warum ist Netcologne für Informatiker interessant?:\n"
    "Die Arbeit bei Netcologne ist sehr vielfältig, Netcologne bietet verschiedene Arbeitsstellen an.\n"
    "\n"
    "## Historie:\n"
    "Netcologne wurde 1994 gegründet und verlegte seit 1995 Glasfaserkabel\n"
    "Neben Telekom sind sie das einzige Telekommunikationsunternehmen mit eigenem Netz."
    "\n"
    "## Mission/Ziel:\n"
    "Ihr Ziel ist es komplett Köln und teile der Umgebung mit Glasfaser zu vernetzen\n"
    "\n"
    "**Website:**\n"
    "netcologne.de\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "1200+\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Nein\n"
    "\n"
    "**Kontakt:**\n"
    "0221 2222 - 800\n"
    "\n"
    "**Quellen:**\n"
    "*-[1] netcologne.de\n"
    "*-[2] netcologne-unternehmen.de\n"
)

IMAGE_NAME = "netcologne_logo.png"
