# id:4

TITEL = "Netflix"

CONTENT = (
    "## Beschreibung:\n"
    "Netflix, Inc. ist ein US-amerikanisches Medienunternehmen, das sich mit dem kostenpflichtigen Streaming und der "
    "Produktion von Filmen und Serien beschäftigt. Das Unternehmen wurde von Reed Hastings und Marc Randolph 1997 im "
    "kalifornischen Los Gatos gegründet und agierte zunächst als Online-Videothek mit dem Versand von Filmen auf DVD "
    "und Blu-ray an seine Abonnenten. 2007 stieg Netflix ins Video-on-Demand-Geschäft ein und machte die Inhalte per "
    "Streaming für Abonnenten zugänglich. Bis März 2020 hatte der Mediendienst knapp 3000 Film- und Fernsehsendungen "
    "als Streaming angeboten. Bis Ende März 2022 wurden bei Netflix seit der Unternehmensgründung 221,64 Millionen "
    "bezahlte Abonnements abgeschlossen, davon 74,58 Millionen in den USA und Kanada [1].\n "
    "\n"
    "## Warum ist Netflix für Informatiker interessant?:\n"
    "Netflix bietet für Informatiker eine attraktive Umgebung mit großen, komplexen Software-Plattformen, "
    "die auf Algorithmen, Datenanalyse und künstlicher Intelligenz basieren. Hier können sie an der Entwicklung und "
    "Verbesserung der Streaming-Plattform arbeiten, Empfehlungssysteme optimieren und innovative Technologien für "
    "Video-Streaming entwickeln. Die Firma bietet zudem ein Umfeld, das auf fortgeschrittenen Technologien und "
    "skalierbaren Infrastrukturen basiert.\n "
    "\n"
    "## Historie:\n"
    "Netflix wurde am 29. August 1997 im kalifornischen Scotts Valley von Marc Randolph und Reed Hastings gegründet ["
    "1]. Anfangs agierte Netflix als Online-Portal und verlieh und verkaufte DVDs und Blu-rays. Im Jahr 2007 startete "
    "Netflix seinen heute bekannten Streaming-Dienst. Seit 2010 war Netflix nicht mehr nur in den Vereinigten Staaten "
    "verfügbar, sondern weitete sich zunächst nach Kanada und zwei Jahre später nach Europa aus [2]. Seit 2014 ist "
    "der Anbieter auch in Deutschland verfügbar2. Noch im selben Jahr machte Netflix erstmalig über eine Milliarde "
    "US-Dollar Umsatz.\n "
    "\n"
    "## Mission/Ziel:\n"
    "Das Ziel bei Netflix ist es, die Welt zu unterhalten. Was auch immer Ihr Geschmack ist und wo auch immer Sie "
    "leben, wir bieten Ihnen Zugang zu erstklassigen Serien, Dokumentationen, Spielfilmen und Mobile Games [3].\n "
    "\n"
    "**Website:**\n"
    "https://www.netflix.com\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "Ca. 12.800 Vollzeitmitarbeiter 2022 [4].\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Ja (Software Enginner Intern (Summer 2024) & Machine Learning Intern, Research (Summer 2024))\n"
    "\n"
    "**Kontakt:**\n"
    "https://jobs.netflix.com/search?team=Internship\n"
    "\n"
    "**Quellen:**\n"
    "*-[Image] https://www.iconfinder.com/icons/4375011/logo_netflix_icon\n"
    "*-[1] https://de.wikipedia.org/wiki/Netflix\n"
    "*-[2] https://praxistipps.chip.de/seit-wann-gibt-es-netflix-die-geschichte-des-streaming-dienstes_101143\n"
    "*-[3] https://de.statista.com/themen/1840/netflix/\n"
    "*-[4] https://www.giga.de/artikel/wem-gehoert-netflix-einfach-erklaert/\n"
)

IMAGE_NAME = "netflix_logo.png"
