# id:63

TITEL = "Porsche"

CONTENT = (
    "## Beschreibung:\n"
    "Die Dr. Ing. h.c. F. Porsche AG, meistens kurz Porsche AG, ist ein deutscher Automobilhersteller, der sich auf "
    "die Herstellung von Hochleistungssportwagen, SUVs und Limousinen spezialisiert hat. Das Unternehmen wurde 1931 "
    "von Dr. Ferdinand Porsche, Adolf Rosenberger und Anton Piëch gegründet [1]. Die Hauptbüros befanden sich in der "
    "Kronenstraße 24 im Zentrum von Stuttgart. Ursprünglich bot das Unternehmen Entwicklungsarbeiten und Beratung für "
    "Kraftfahrzeuge an, baute jedoch keine Autos unter eigenem Namen. Eines der ersten Aufträge, die das neue "
    "Unternehmen erhielt, kam von der deutschen Regierung, um ein Auto für das Volk zu entwerfen, das heißt, "
    "einen Volkswagen. Dies führte zum Volkswagen Käfer, einem der erfolgreichsten Automobildesigns aller Zeiten ["
    "1].\n "
    "\n"
    "## Warum ist Porsche für Informatiker interessant?:\n"
    "Porsche ist für Informatiker attraktiv aufgrund der Möglichkeit, an der Entwicklung moderner Technologien für "
    "zukünftige Fahrzeuge mitzuarbeiten. Das Unternehmen investiert in Elektromobilität, autonomes Fahren und "
    "digitale Dienste, was Informatikern die Chance bietet, an innovativen Projekten im Automobilbereich zu arbeiten "
    "und sich persönlich weiterzuentwickeln.\n "
    "\n"
    "## Historie:\n"
    "Die Geschichte von Porsche beginnt im Jahr 1931, als das Unternehmen von Dr. Ferdinand Porsche, "
    "Adolf Rosenberger und Anton Piëch gegründet wurde. Ursprünglich als Hersteller von Flugzeugmotoren gegründet, "
    "produzierte Porsche von 1917 bis 1918 und erneut von 1933 bis 1945 Flugzeugmotoren [1].\n "
    "Im Jahr 1948 stellte Porsche den aerodynamischen “356” vor, benannt nach seiner Designprojektnummer. Bis 1949 "
    "wurden die ersten 52 Autos in einer kleinen Garage in Gmünd, Österreich, handgefertigt. 1950 mietete Porsche "
    "Platz in der Reutter-Karosseriefabrik in Zuffenhausen, einem Vorort von Stuttgart. Reutter baute Karosserien für "
    "den 356, und die Produktion erreichte 369 Stück im Jahr. Sportwagenenthusiasten nahmen den leichten, schnell zu "
    "handhabenden 356 zur Kenntnis [2].\n "
    "\n"
    "## Mission/Ziel:\n"
    "Die Mission von Porsche ist es, einwandfreien Service für die anspruchsvolle Kundschaft von Premium-Autos zu "
    "bieten. Porsche strebt danach, Synergien zu maximieren und High-End-Lösungen gemeinsam für die Kunden zu "
    "schaffen. Porsche bekennt sich zum Pariser Klimaschutzabkommen und setzt sich Ziele, die darüber hinausgehen [3] "
    "[6].\n "
    "\n"
    "**Website:**\n"
    "https://www.porsche.com/germany/\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "Im Jahr 2022 beschäftigte die Porsche AG weltweit ca. 39.162 Mitarbeiter [4] [5].\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Ja\n"
    "\n"
    "**Kontakt:**\n"
    "https://jobs.porsche.com/index.php?ac=search_result&search_criterion_entry_level%5B%5D=5\n"
    "\n"
    "**Quellen:**\n"
    "*-[Image] https://de.wikipedia.org/wiki/Datei:Porsche_Logo.svg\n"
    "*-[1] https://de.wikipedia.org/wiki/Porsche\n"
    "*-[2] https://press.porsche.com/prod/presse_pag/PressResources.nsf/jumppage/unternehmen-pcna-history\n"
    "*-[3] https://www.porschespokane.com/history-of-porsche/\n"
    "*-[4] https://www.mbaknol.com/business-history/history-and-background-of-porsche/\n"
    "*-[5] https://de.statista.com/statistik/daten/studie/291631/umfrage/mitarbeiter-von-porsche/\n"
    "*-[6] https://www.porsche.com/germany/aboutporsche/e-performance/magazine/mission-vision/\n"
)

IMAGE_NAME = "porsche.png"
