# id:5

TITEL = "Space X"

CONTENT = (
    "## Beschreibung:\n"
    "Heute ist SpaceX ein führendes globales Luft- und Raumfahrtunternehmen, das kommerzielle Flugzeuge, "
    "Verteidigungsprodukte und Weltraumsysteme für Kunden in mehr als 150 Ländern entwickelt, herstellt und wartet. "
    "Als einer der größten US-Exporteure nutzt das Unternehmen die Talente einer globalen Lieferantenbasis, "
    "um wirtschaftliche Chancen, Nachhaltigkeit und gesellschaftliche Auswirkungen voranzutreiben [3] [4]. Die "
    "Geschäftseinheiten von SpaceX sind um drei Hauptgruppen von Produkten und Dienstleistungen organisiert - "
    "kommerzielle Flugzeuge, Militärflugzeuge und Raketen sowie Raumfahrt und Kommunikation. SpaceX stellt sieben "
    "verschiedene Familien von Verkehrsflugzeugen her, die in zwei Einrichtungen - Renton und Everett - im "
    "Bundesstaat Washington montiert werden [3].\n "
    "\n"
    "## Warum ist Space X für Informatiker interessant?:\n"
    "SpaceX ist ein äußerst attraktives Unternehmen für Informatiker aufgrund seiner Vorreiterrolle in der "
    "Raumfahrttechnologie. Informatiker haben die Chance, an der Entwicklung fortschrittlicher Raumfahrtsysteme, "
    "Raketen, Kommunikationstechnologien und Satelliten mitzuwirken. Zudem bietet das Unternehmen spannende "
    "Möglichkeiten, an bedeutenden Weltraummissionen und der Marskolonisierung teilzunehmen, was ein einzigartiges "
    "und faszinierendes Arbeitsumfeld schafft.\n "
    "\n"
    "## Historie:\n"
    "SpaceX, auch bekannt als Space Exploration Technologies, ist ein amerikanischer Raumfahrzeughersteller und "
    "Anbieter von Raumfahrt-Dienstleistungen, der 2002 von Elon Musk gegründet wurde [1][2]. Nachdem Musk Ende 2000 "
    "als CEO von PayPal entlassen wurde, begann er, sich für Raumfahrtprojekte zu interessieren. Diese Interesse "
    "entstand, als er von seinem Freund und Unternehmer Adeo Ressi gefragt wurde, was seine Pläne für die Zukunft "
    "nach PayPal seien [1]. Musk schaute auf die NASA-Website und war überrascht, dass die NASA keinen konkreten Plan "
    "für eine bemannte Marsmission hatte [1]. Daraufhin begann er, Raumfahrtkonferenzen zu besuchen und private "
    "Raumfahrtprojekte zu finanzieren. Musk reiste zweimal nach Russland, um eine überholte Interkontinentalrakete "
    "für das Mars Oasis-Projekt zu beschaffen, aber beide Versuche scheiterten. Nach dem zweiten gescheiterten "
    "Versuch, eine Rakete zu beschaffen, gab Musk den Mars Oasis-Plan auf und überlegte, ob es machbar wäre, "
    "selbst eine Rakete zu bauen[1].\n "
    "\n"
    "## Mission/Ziel:\n"
    "Das Ziel von SpaceX ist es, Technologien zu entwickeln, die es der Menschheit ermöglichen sollen, den Mars zu "
    "kolonisieren und das Leben auf anderen Planeten zu verbreiten.\n "
    "\n"
    "**Website:**\n"
    "https://www.spacex.com/\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "13.000+ (September 2023)\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Ja\n"
    "\n"
    "**Quellen:**\n"
    "*-[Image] https://in.pinterest.com/pin/spacex-logo-png-images-transparent-hd-photo-clipart--577023771024040752/\n"
    "*-[1] https://en.wikipedia.org/wiki/History_of_SpaceX\n"
    "*-[2] https://www.britannica.com/topic/SpaceX\n"
    "*-[3] https://simple.wikipedia.org/wiki/SpaceX\n"
    "*-[4] https://www.spacex.com/\n"
    "*-[5] https://www.spacex.com/launches/\n"
    "\n"
)

IMAGE_NAME = "spacex.png"
