# id:54

TITEL = "Carl Zeiss"

CONTENT = (
    "## Beschreibung:\n"
    "Die Carl Zeiss AG, gegründet 1846 in Jena, Deutschland, ist weltweit führend in der Herstellung hochwertiger "
    "optischer Produkte und Präzisionstechnologien. Das Unternehmen bietet Objektive für Kameras, Ferngläser, "
    "Mikroskope, medizinische Bildgebungssysteme und Lasertechnologie an. Zusätzlich ist es in der Medizintechnik "
    "sowie der Halbleiterfertigung tätig. Zeiss ist bekannt für seine Innovationskraft, Qualität und seine bedeutende "
    "Rolle in verschiedenen Branchen, die auf optische Technologien angewiesen sind.\n "
    "\n"
    "## Warum ist die Carl Zeiss AG für Informatiker interessant?:\n"
    "ZEISS ist ein attraktiver Arbeitgeber für Informatiker aufgrund seiner Spezialisierung in Optik und "
    "Optoelektronik. Die Firma bietet spannende Entwicklungs- und Gestaltungsmöglichkeiten für moderne "
    "Bildverarbeitungstechnologien, hochpräzise Messsysteme und innovative medizinische Geräte. Informatiker haben "
    "hier die Chance, ihre Fähigkeiten in Bereichen wie Medizintechnik, Mikroskopie, Halbleiterfertigung und Virtual "
    "Reality einzubringen.\n "
    "\n"
    "## Historie:\n"
    "Die Carl Zeiss AG hat eine reiche und bedeutende Vergangenheit, die bis ins 19. Jahrhundert zurückreicht. Das "
    "Unternehmen wurde im Jahr 1846 von dem Optiker Carl Zeiss in Jena, Deutschland, gegründet. Bereits in den frühen "
    "Jahren seiner Gründung konzentrierte sich Zeiss auf die Herstellung hochwertiger optischer Instrumente wie "
    "Mikroskope und Fernrohre, die für ihre Präzision und Qualität bekannt wurden. In den späteren Jahren des 19. "
    "Jahrhunderts setzte Zeiss seinen Weg als Innovator in der optischen Industrie fort, indem es neue "
    "Fertigungstechniken einführte und hochentwickelte optische Geräte herstellte. Die Produkte von Zeiss erlangten "
    "schnell weltweite Anerkennung und das Unternehmen etablierte sich als einer der führenden Hersteller in seinem "
    "Bereich. Im 20. Jahrhundert expandierte Carl Zeiss AG in verschiedene Bereiche der Optik und entwickelte eine "
    "breite Produktpalette, einschließlich hochwertiger Objektive für Kameras, Ferngläser, Mikroskope sowie "
    "medizinische Bildgebungssysteme. Zeiss setzte immer wieder Maßstäbe in der optischen Technologie und trug "
    "entscheidend zur wissenschaftlichen Forschung, medizinischen Bildgebung und anderen Branchen bei, "
    "die auf hochpräzise optische Instrumente angewiesen sind. Die Geschichte von Carl Zeiss AG ist auch mit "
    "bedeutenden technologischen Durchbrüchen verbunden, insbesondere in der Medizintechnik. Das Unternehmen spielte "
    "eine entscheidende Rolle bei der Entwicklung fortschrittlicher Geräte für die Augenchirurgie, diagnostische "
    "Instrumente und andere medizinische Anwendungen. Durch Innovation, Forschung und konstante Weiterentwicklung hat "
    "sich die Carl Zeiss AG als einer der angesehensten und führenden Hersteller von optischen Produkten weltweit "
    "etabliert und hinterlässt eine reiche Geschichte in der optischen Industrie.\n "
    "\n"
    "## Mission/Ziel:\n"
    "Die Ziele der Carl Zeiss AG sind vielfältig und umfassen verschiedene Aspekte ihres Geschäftsbetriebs. Als "
    "Unternehmen in der optischen Industrie strebt Zeiss kontinuierliche Innovation und Forschung an, um wegweisende "
    "optische Technologien und Produkte zu entwickeln. Das Unternehmen legt großen Wert auf hochwertige Produkte und "
    "Technologien, sei es in der Kameratechnik, medizinischen Geräten, Mikroskopen oder anderen optischen "
    "Anwendungen. Die Zielsetzung liegt dabei auf Präzision, Qualität und Leistungsfähigkeit. Ein weiteres "
    "bedeutendes Ziel von Zeiss ist es, die Kundenzufriedenheit zu steigern, indem die Bedürfnisse und Anforderungen "
    "der Kunden erfüllt werden. Durch eine enge Zusammenarbeit und maßgeschneiderte Lösungen bemüht sich Zeiss, "
    "die Erwartungen seiner Kunden zu übertreffen. Darüber hinaus setzt Zeiss auf Nachhaltigkeit und soziale "
    "Verantwortung. Das Unternehmen engagiert sich für umweltfreundliche Produktionsprozesse und Ressourceneffizienz, "
    "um eine nachhaltige Geschäftstätigkeit zu gewährleisten. Ein weiteres Ziel besteht darin, die internationale "
    "Präsenz von Zeiss zu stärken und das Unternehmenswachstum in verschiedenen Regionen weltweit voranzutreiben. "
    "Zeiss strebt nach Möglichkeiten, seine Geschäftstätigkeit global auszubauen und neue Märkte zu erschließen. "
    "Insgesamt zielt die Carl Zeiss AG darauf ab, durch Innovation, hochwertige Produkte, Kundenzufriedenheit, "
    "Nachhaltigkeit und internationales Wachstum ihre führende Position als renommierter Hersteller von optischen "
    "Produkten und Technologien weiter zu festigen und auszubauen.\n "
    "\n"
    "**Website:**\n"
    "https://www.zeiss.de\n"
    "\n"
    "**Mitarbeiterzahl:**\n"
    "Das Unternehmen beschäftigt zum Stand 2023 über 40.000 Mitarbeiter/innen\n"
    "\n"
    "**Praxissemester/Praktikum:**\n"
    "Ja\n"
    "\n"
    "**Kontakt:**\n"
    "Carl Zeiss AG\nCarl-Zeiss-Straße 22\n73447 Oberkochen\nDeutschland\nTelefon: +49 7364 20-0\nTelefax: +49 7364 "
    "20-6808\n "
    "\n"
    "**Quellen:**\n"
    "*-Bild: https://www.google.com/imgres?imgurl=https%3A%2F%2Fimage.capital.de%2F31039336%2Ft%2FLT%2Fv1%2Fw1440"
    "%2Fr1.3333%2F-%2Fzeiss-tor-pr-jpg.jpg&tbnid=XGUDuEhh5j7wgM&vet=12ahUKEwj8ys_X7uaCAxUxXaQEHauZAhUQMygBegUIARCsAQ"
    "..i&imgrefurl=https%3A%2F%2Fwww.capital.de%2Fwirtschaft-politik%2Fwestern-von-gestern-der-kalte-krieg-um-carl"
    "-zeiss-8694&docid=qbhBNDd_valjWM&w=1440&h=1080&q=zeiss&hl=de&ved=2ahUKEwj8ys_X7uaCAxUxXaQEHauZAhUQMygBegUIARCsAQ"
    "\n "
    "*-https://www.zeiss.de/home/überuns\n"
    "*-https://www.zeiss.de/dam/history\n"
)

IMAGE_NAME = "zeiss.png"
